{
 "title": "k8s-vgpu-scheduler Dashboard",
 "description": "This dashboard is gpu metrics dashboard base on NVIDIA DCGM Exporter and k8s-vgpu-scheduler",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "query": {
     "query": "label_values({__name__=~\"DCGM_FI_DEV_FB_FREE|vGPU_device_memory_limit_in_bytes\"}, node_name)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(DCGM_FI_DEV_FB_FREE{node_name=\"$node_name\"},gpu)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU平均温度",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{node_name=~\"${node_name}\", gpu=~\"${gpu}\"})"
    }
   ]
  },
  {
   "title": "GPU总功率",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{node_name=~\"${node_name}\", gpu=~\"${gpu}\"})"
    }
   ]
  },
  {
   "title": "GPU温度",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{node_name=~\"${node_name}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{node_name}} gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU SM时钟频率(DCGM_FI_DEV_SM_CLOCK)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{node_name=~\"${node_name}\", gpu=~\"${gpu}\"} * 1000000",
     "legendFormat": "{{node_name}} gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU帧缓存（显存）使用量(DCGM_FI_DEV_FB_USED)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{node_name=~\"${node_name}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{node_name}} gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU功率消耗(DCGM_FI_DEV_POWER_USAGE)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{node_name=~\"${node_name}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{node_name}} gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU利用率(DCGM_FI_DEV_GPU_UTIL)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{node_name=~\"${node_name}\", gpu=~\"${gpu}\"}",
     "legendFormat": "{{node_name}} gpu{{gpu}}"
    }
   ]
  },
  {
   "title": "pod显存使用量（byte）",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Device_memory_desc_of_container{node_name=~\"${node_name}\"}",
     "legendFormat": "{{podname}}"
    }
   ]
  },
  {
   "title": "节点GPU显存使用量",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "HostGPUMemoryUsage{node_name=~\"${node_name}\"}",
     "legendFormat": "{{node_name}} gpu {{deviceid}}"
    }
   ]
  },
  {
   "title": "节点GPU算力使用率",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "HostCoreUtilization{node_name=~\"${node_name}\"}",
     "legendFormat": "{{node_name}} gpu {{deviceid}}"
    }
   ]
  }
 ]
}